#!/bin/bash
apt update && apt install wget -y
cd /tmp && wget https://go.dev/dl/go1.19.4.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.19.4.linux-amd64.tar.gz
chown -R root:root /usr/local/go
echo "export PATH=$PATH:/usr/local/go/bin" > ~/.profile
source ~/.profile
rm go1.19.4.linux-amd64.tar.gz